#!/bin/sh -x
###
# This program was written by and is copyright Alec Muffett 1991,
# 1992, 1993, 1994, 1995, and 1996, and is provided as part of the
# Crack v5.0 Password Cracking package.
#
# The copyright holder disclaims all responsibility or liability with
# respect to its usage or its effect upon hardware or computer
# systems, and maintains copyright as set out in the "LICENCE"
# document which accompanies distributions of Crack v5.0 and upwards.
###
# for tidying master dictionaries

tfile=.dtt$$

for dict in $*
do
	grep '^#' $dict > $tfile
	grep -v '^#' $dict | sort | uniq >> $tfile
	mv $dict $dict~
	mv $tfile $dict
done

exit 0

