#!/bin/sh
###
# This program was written by and is copyright Alec Muffett 1991,
# 1992, 1993, 1994, 1995, and 1996, and is provided as part of the
# Crack v5.0 Password Cracking package.
#
# The copyright holder disclaims all responsibility or liability with
# respect to its usage or its effect upon hardware or computer
# systems, and maintains copyright as set out in the "LICENCE"
# document which accompanies distributions of Crack v5.0 and upwards.
###
# Make a dictionary group.  Assume called from $CRACK_HOME with
# suitable path

if [ "x$2" = "x" ]
then
	echo "Usage: $0 outfile infiles..." 1>&2
	exit 1
fi

outfile=$1

shift

smartcat $* |
	grep -v '^#' |
	crack-sort |
	uniq > $outfile

exit 0
